targets:
  $default:
    builders:
      # freezed:
      #   options:
      #     union_key: runtime_type
      #     union_value_case: snake
      json_serializable:
        options:
          include_if_null: false
          create_field_map: true
